### ISSUE TITLE
WRF install:Maybe can add clean or judge function

### ISSUE THREAD

**Issue by tomtomtomtony** [SettRaziel/wrf_archlinux#53]
**Describe the bug**
It's an amazing work. However, there are some suggestions.
First, maybe can add some judge function to  judge user whether have installed some Library;
Second , maybe can add some judge function to judge user whether rerun the run_install;
Third, maybe can add a clean function after the user rerun the install_wrf.sh;

For most archlinuxer,they have installed yay software, so it's maybe a good idea to judge whether user have installed some libraries and software;

The install_wrf.sh may be broken for computer power off or other reason, so user has to rerun the  install_wrf.sh. However, for example, there is on judge function, the install_wrf.sh will prompt "the yay folder has existed", "the /lib/cpp has existed" and so on.

**Comment by SettRaziel** [comment]
Hi there.
Thanks for your feedback. I would like to comment on your points, since i need some additional information to reply properly.

* In the first point and the second paragraph you suggest to check if a given library is installed. Can you elaborate on this topic? The usage of the --needed flag for the package manager only takes the package actions if the package is outdated or not installed. If you already have the most recent version the command will be skipped. If you are talking about the required WRF dependencies it is not feasible to check if some libraries are already installed through the package manager, since additional flags or directories are required for most of the dependencies. A sanity check for the dependencies that are installed is implicitly done through configure and make.
* At this moment i do not see a feasibly way to do a consistency check for the installation process to find the point from which the installation should be rerun. If the installation was successfully i do not see the necessity to rerun the installation.
* The installation scripts already check and clean up previous installations, if the destination folder already exists.
* The last point is correct. Some existing warnings will lead to this problem in some cases or when reinstalling the model repeatedly. I will check that and create a new issue for that soon.

**Comment by SettRaziel** [comment]
Hi.
I addressed your points and added another issue (#54) to handle the problems that could lead to an abortion of the model installation when rerunning it.
Since your did not have any comments to that i would close the issue. Please feel free to add addtional feedback by reopening this issue, if you have additional point.

**Comment by tomtomtomtony** [comment]
> Hi.
> I addressed your points and added another issue (#54) to handle the problems that could lead to an abortion of the model installation when rerunning it.
> Since your did not have any comments to that i would close the issue. Please feel free to add addtional feedback by reopening this issue, if you have additional point.

I'm very sorry to reply you so late. I read your reply detailly, I misunderstand some knowledge of  Linux, I think. Thank you.
