### ISSUE TITLE
Question: Feedback for WRF Scripts

### ISSUE THREAD

**Issue by fnag-met** [SettRaziel/wrf_archlinux#75]
Hello! I will test your code in my laptop with Manjaro. I am new in Git hub for that reazon i will read all the documentation. And then i will try to install the WRF model. Any sugestion before install the model. Thanks.

**Comment by SettRaziel** [comment]
Hej there.
Welcome to github then. I took the liberty to edit the headline and the text of your issue.
I will give you detailed feedback after work, so stand by please.

**Comment by SettRaziel** [comment]
Hello again.
Before diving to the feedback for the WRF Model that you requested, maybe it is a good idea to share my view regarding issues in github.

Since a solid discussion point for questions within a repository is not (yet: https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions) available for the platform it is a reasonable way to start a discussion by opening an issue within the repository. But you can also get feedback by writing a mail. Most of the time you will find that when been logged in and visiting a user profile.
To confuse you even further, you could also create an empty issue within this repository. The bug form is the default template i put into this repository, but you could also click on the link "Open a blank issue". Independent from the issue template you use you should give a short title and provide your message or issue in the text field below.

You could also get the code for this project without an account. But if you want to contribute or discuss things on the platform an account is a good idea.

With that being said, it is time to give you the feedback to the main subject:
Before i can give you any advice it would be helpful to know, what is the goal for which you will use it. Do you want to install the model on your machine for any reason or to test some other things (e.g. the hybrid coordinates) that are not considered in the installation right now?
Do you want to run the model and produce visible results like the png files that are created at the moment?
Or do you want to run the model and process the output data with further things?

If you want to run the model i can only recommend to use the deployment feature that i associated with the wrf_deploy subproject. With that you will download and deploy an already precompiled archive with the required libraries and set up an environment where only a few additional steps are necessary to start a model run.
If you want to install the model by yourself for any reason be advised that it will only setup the model and its required dependencies but you have to do all additional steps: directory structure, geographical data, correct script placement.

A last point to consider: You will install a number of additional libraries and dependencies on the machine when building or deploying the WRF sources. You might want to consider using a virtual machine or even a container solution. I do have a docker file in another repository but it is not finished and i am afraid it is not working as i would hope it would.
For testing purposes i have a virtual machine on my local laptop or you could use a virtual server at a hoster of your choosing.

Feel free to give feedback or additional comment in this issue. If the question is answered for you please drop a note so i can close this issue. Thank you.

**Comment by fnag-met** [comment]
Dear Benjamin.

Thanks for the comments. As I mentioned i am new in github, i would like to
contribute to your work with my experience, i have revised all the codes
and i am agree with you. It is  a great job.

I will document my experience in WRF. But first i would like to introduce
me.

I am writing you from Mexico City, I am working in the National Weather
Service in México City (https://smn.conagua.gob.mx/es/). I am physicist and
I am doing my PhD in data assimilation in the Center of Atmospheric Sciencs
(https://www.atmosfera.unam.mx/) at Universidad Nacional Autónoma de
México. Some friends have help me to install WRF in a server but i woul
like to learn to instal the model in my personal computer.

I will try to be in contact with you once a week o two weeks i know that
you have your own activities and i believe that your work in  this project
in your free time.

I forgot to mention that I used to work with NCL, I did all the scripts to
plot all the products in this site (
http://grupo-ioa.atmosfera.unam.mx/pronosticos/index.php/meteorologia)

Last year I started to learn python and i am learning as much as possible,
to plot WRF outputs with python.

I think that your project is great and I hope to contribute with something.

Greetings from México City
I attached a picture from my house.

Fernando Arellano Guerreri

**Comment by SettRaziel** [comment]
Hej Fernando.
Thanks for your feedback. 
I switched from NCL to wrf-python recently (#73) and will update to the new output visualization that i have published [here](https://github.com/SettRaziel/wrf_visualization) on my servers shortly. Unfortunately the python approach from the NCAR stills lags several routines i know from my NCL scripts. Hopefully they fix these things in the near future.
I am trying to build infrastructure around the output to present the output i an better way.
In the meantime i will start to compile and package the newest version WRF 4.2 (#74)  and update the deployment pipeline when the compile process ran successfully in my building environment.
Feel free to add further comments via e-mail if you like. You can find the address in my profile.

Best regards,
Benjamin.
